// user-vue/src/pages/contact/index.vue
<template>
  <div class="contact">
    <div class="banner">
      <CustomerServiceOutlined class="banner-icon" />
      <h1 class="banner-title">{{ t('contact.title') }}</h1>
      <p class="banner-desc">{{ t('contact.subtitle') }}</p>
    </div>

    <div class="container">
      <a-row :gutter="[24, 24]">
        <a-col :xs="24" :md="12">
          <a-card class="info-card">
            <h2 class="section-title">{{ t('contact.contactWay') }}</h2>

            <div class="contact-item">
              <MailOutlined class="contact-icon" />
              <div>
                <h4>{{ t('contact.email') }}</h4>
                <p>support@crossbordershop.com</p>
                <p class="note">{{ t('contact.emailNote') }}</p>
              </div>
            </div>

            <div class="contact-item">
              <PhoneOutlined class="contact-icon" />
              <div>
                <h4>{{ t('contact.phone') }}</h4>
                <p>+86-123-4567-8900</p>
                <p class="note">{{ t('contact.phoneNote') }}</p>
              </div>
            </div>

            <div class="contact-item">
              <EnvironmentOutlined class="contact-icon" />
              <div>
                <h4>{{ t('contact.address') }}</h4>
                <p>{{ t('contact.addressDetail') }}</p>
                <p class="note">{{ t('contact.addressNote') }}</p>
              </div>
            </div>

            <div class="contact-item">
              <ClockCircleOutlined class="contact-icon" />
              <div>
                <h4>{{ t('contact.workTime') }}</h4>
                <p>{{ t('contact.workTimeWeekday') }}</p>
                <p>{{ t('contact.workTimeWeekend') }}</p>
              </div>
            </div>
          </a-card>
        </a-col>

        <a-col :xs="24" :md="12">
          <a-card class="form-card">
            <h2 class="section-title">{{ t('contact.sendMessage') }}</h2>
            <p class="form-desc">{{ t('contact.formDesc') }}</p>

            <a-form ref="formRef" :model="formData" layout="vertical" @finish="handleSubmit">
              <a-form-item
                name="name"
                :label="t('contact.name')"
                :rules="[{ required: true, message: t('common.required') }]"
              >
                <a-input v-model:value="formData.name" :placeholder="t('contact.namePlaceholder')" />
              </a-form-item>

              <a-form-item
                name="email"
                :label="t('contact.email')"
                :rules="[
                  { required: true, message: t('common.required') },
                  { type: 'email', message: t('contact.emailInvalid') },
                ]"
              >
                <a-input v-model:value="formData.email" placeholder="your@email.com" />
              </a-form-item>

              <a-form-item
                name="subject"
                :label="t('contact.subject')"
                :rules="[{ required: true, message: t('common.required') }]"
              >
                <a-input v-model:value="formData.subject" :placeholder="t('contact.subjectPlaceholder')" />
              </a-form-item>

              <a-form-item
                name="message"
                :label="t('contact.message')"
                :rules="[{ required: true, message: t('common.required') }]"
              >
                <a-textarea
                  v-model:value="formData.message"
                  :rows="6"
                  :placeholder="t('contact.messagePlaceholder')"
                />
              </a-form-item>

              <a-form-item>
                <a-button type="primary" html-type="submit" block size="large" :loading="loading">
                  {{ t('contact.submit') }}
                </a-button>
              </a-form-item>
            </a-form>
          </a-card>
        </a-col>
      </a-row>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useI18n } from '@/i18n'
import { message } from 'ant-design-vue'
import type { FormInstance } from 'ant-design-vue'
import {
  CustomerServiceOutlined,
  MailOutlined,
  PhoneOutlined,
  EnvironmentOutlined,
  ClockCircleOutlined,
} from '@ant-design/icons-vue'

const { t } = useI18n()
const formRef = ref<FormInstance>()
const loading = ref(false)

const formData = ref({
  name: '',
  email: '',
  subject: '',
  message: '',
})

const handleSubmit = async () => {
  try {
    loading.value = true
    console.log('Contact form submitted:', formData.value)
    message.success(t('contact.submitSuccess'))
    formRef.value?.resetFields()
  } catch (error) {
    console.error('Failed to submit contact form:', error)
    message.error(t('common.error'))
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.contact {
  background: #f5f5f5;
}

.banner {
  background: linear-gradient(135deg, #1890ff 0%, #0050b3 100%);
  color: white;
  padding: 80px 24px;
  text-align: center;
}

.banner-icon {
  font-size: 48px;
  display: block;
  margin-bottom: 16px;
}

.banner-title {
  font-size: 42px;
  font-weight: bold;
  margin: 0;
}

.banner-desc {
  font-size: 18px;
  margin-top: 12px;
  opacity: 0.9;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 48px 24px;
}

.info-card,
.form-card {
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.1);
}

.section-title {
  font-size: 20px;
  font-weight: bold;
  margin: 0 0 24px;
}

.contact-item {
  display: flex;
  gap: 16px;
  margin-bottom: 24px;
}

.contact-item:last-child {
  margin-bottom: 0;
}

.contact-icon {
  font-size: 24px;
  color: #667eea;
  flex-shrink: 0;
  margin-top: 4px;
}

.contact-item h4 {
  font-size: 16px;
  font-weight: bold;
  margin: 0 0 4px;
}

.contact-item p {
  color: #666;
  margin: 0 0 4px;
  font-size: 14px;
}

.contact-item p:last-child {
  margin-bottom: 0;
}

.note {
  color: #999;
  font-size: 12px !important;
}

.form-desc {
  color: #666;
  margin-bottom: 24px;
  font-size: 14px;
}

@media (max-width: 768px) {
  .banner {
    padding: 48px 16px;
  }

  .banner-title {
    font-size: 28px;
  }

  .banner-desc {
    font-size: 14px;
  }

  .container {
    padding: 24px 16px;
  }

  .section-title {
    font-size: 16px;
  }
}
</style>

// user/src/pages/contact/index.tsx
import React from "react";
import { Typography, Card, Row, Col, Form, Input, Button } from "antd";
import {
  MailOutlined,
  PhoneOutlined,
  EnvironmentOutlined,
  ClockCircleOutlined,
  CustomerServiceOutlined,
} from "@ant-design/icons";
import { useTranslation } from "react-i18next";
import styles from "./index.module.css";

const { Title, Paragraph } = Typography;
const { TextArea } = Input;

const Contact: React.FC = () => {
  const { t } = useTranslation();
  const [form] = Form.useForm();

  const handleSubmit = (values: any) => {
    console.log("Contact form submitted:", values);
    // 这里暂时不发送网络请求
    form.resetFields();
  };

  return (
    <div className={styles.contact}>
      <div className={styles.banner}>
        <CustomerServiceOutlined className={styles.bannerIcon} />
        <Title level={1} className={styles.bannerTitle}>
          联系我们
        </Title>
        <Paragraph className={styles.bannerDesc}>
          我们随时为您提供帮助和支持
        </Paragraph>
      </div>

      <div className={styles.container}>
        <Row gutter={[24, 24]}>
          <Col xs={24} md={12}>
            <Card className={styles.infoCard}>
              <Title level={2} className={styles.sectionTitle}>
                联系方式
              </Title>

              <div className={styles.contactItem}>
                <MailOutlined className={styles.contactIcon} />
                <div>
                  <Title level={4}>电子邮箱</Title>
                  <Paragraph>support@crossbordershop.com</Paragraph>
                  <Paragraph className={styles.note}>
                    我们会在24小时内回复您的邮件
                  </Paragraph>
                </div>
              </div>

              <div className={styles.contactItem}>
                <PhoneOutlined className={styles.contactIcon} />
                <div>
                  <Title level={4}>客服电话</Title>
                  <Paragraph>+86-123-4567-8900</Paragraph>
                  <Paragraph className={styles.note}>
                    服务时间：周一至周五 9:00-18:00
                  </Paragraph>
                </div>
              </div>

              <div className={styles.contactItem}>
                <EnvironmentOutlined className={styles.contactIcon} />
                <div>
                  <Title level={4}>公司地址</Title>
                  <Paragraph>中国上海市浦东新区世纪大道1000号</Paragraph>
                  <Paragraph className={styles.note}>欢迎预约到访</Paragraph>
                </div>
              </div>

              <div className={styles.contactItem}>
                <ClockCircleOutlined className={styles.contactIcon} />
                <div>
                  <Title level={4}>工作时间</Title>
                  <Paragraph>周一至周五：9:00 - 18:00</Paragraph>
                  <Paragraph>周六至周日：10:00 - 17:00</Paragraph>
                </div>
              </div>
            </Card>
          </Col>

          <Col xs={24} md={12}>
            <Card className={styles.formCard}>
              <Title level={2} className={styles.sectionTitle}>
                发送消息
              </Title>
              <Paragraph className={styles.formDesc}>
                有任何问题或建议？请填写表单，我们会尽快回复您。
              </Paragraph>

              <Form form={form} layout="vertical" onFinish={handleSubmit}>
                <Form.Item
                  label="姓名"
                  name="name"
                  rules={[{ required: true, message: "请输入您的姓名" }]}
                >
                  <Input placeholder="请输入您的姓名" size="large" />
                </Form.Item>

                <Form.Item
                  label="电子邮箱"
                  name="email"
                  rules={[
                    { required: true, message: "请输入您的邮箱" },
                    { type: "email", message: "请输入有效的邮箱地址" },
                  ]}
                >
                  <Input placeholder="your@email.com" size="large" />
                </Form.Item>

                <Form.Item
                  label="主题"
                  name="subject"
                  rules={[{ required: true, message: "请输入主题" }]}
                >
                  <Input placeholder="请简要描述您的问题" size="large" />
                </Form.Item>

                <Form.Item
                  label="消息内容"
                  name="message"
                  rules={[{ required: true, message: "请输入消息内容" }]}
                >
                  <TextArea
                    rows={6}
                    placeholder="请详细描述您的问题或建议..."
                    size="large"
                  />
                </Form.Item>

                <Form.Item>
                  <Button type="primary" htmlType="submit" size="large" block>
                    发送消息
                  </Button>
                </Form.Item>
              </Form>
            </Card>
          </Col>
        </Row>
      </div>
    </div>
  );
};

export default Contact;
