// .shop/src/pages/admin/settings/index.tsx
import React, { useEffect, useState } from "react";
import {
  Card,
  Form,
  Input,
  InputNumber,
  Select,
  Switch,
  Button,
  Divider,
  message,
  Row,
  Col,
  Statistic,
  Space,
  Upload,
} from "antd";
import {
  getAppConfig,
  updateAppConfig,
  getSystemStats,
} from "@/services/settings";
import { getCurrencies } from "@/services/rate";
import { uploadProductImages } from "@/services/product";
import type { SystemStats } from "@/models/settings";
import type { Currency } from "@/models/rate";
import type { UploadFile } from "antd";
import dayjs from "dayjs";

const AdminSettings: React.FC = () => {
  const [form] = Form.useForm();
  const [loading, setLoading] = React.useState(false);
  const [stats, setStats] = React.useState<SystemStats | null>(null);
  const [currencies, setCurrencies] = useState<Currency[]>([]);
  const [carouselFiles, setCarouselFiles] = useState<UploadFile[]>([]);

  const getApiBaseUrl = () => {
    const env =
      process.env.REACT_APP_API_BASE_URL || "http://localhost:8080/api";
    if (env.startsWith("http")) {
      return env;
    }
    const normalized = env.startsWith("/") ? env : `/${env}`;
    return `${window.location.origin}${normalized}`;
  };

  const normalizeImageUrl = (url?: string) => {
    if (!url) return url;
    if (url.startsWith("http")) return url;
    const base = getApiBaseUrl();
    const path = url.startsWith("/") ? url : `/${url}`;
    return `${base}${path}`;
  };

  const normalizeImageForSave = (url?: string) => {
    if (!url) return url;
    const base = getApiBaseUrl();
    if (url.startsWith(base)) {
      const rest = url.slice(base.length);
      return rest.startsWith("/") ? rest : `/${rest}`;
    }
    return url;
  };

  useEffect(() => {
    loadSettings();
    loadStats();
    loadCurrencies();
  }, []);

  const loadSettings = async () => {
    try {
      setLoading(true);
      const response = await getAppConfig();
      const carouselImages = response.data?.carouselImages || [];
      setCarouselFiles(
        carouselImages.map((url, index) => ({
          uid: `${index}`,
          name: `carousel-${index}`,
          status: "done",
          url: normalizeImageUrl(url),
        })),
      );
      form.setFieldsValue(response.data);
    } catch (error) {
      message.error("加载配置失败");
    } finally {
      setLoading(false);
    }
  };

  const loadStats = async () => {
    try {
      const response = await getSystemStats();
      setStats(response.data || null);
    } catch (error) {
      console.error("Failed to load stats:", error);
    }
  };

  const loadCurrencies = async () => {
    try {
      const response = await getCurrencies();
      if (response.data) {
        setCurrencies(response.data);
      }
    } catch (error) {
      console.error("Failed to load currencies:", error);
    }
  };

  const handleSave = async () => {
    try {
      const values = await form.validateFields();
      const carouselImages = carouselFiles
        .map((file) => file.response?.data || file.url)
        .map((url) => normalizeImageForSave(url))
        .filter(Boolean) as string[];
      setLoading(true);
      await updateAppConfig({
        ...values,
        carouselImages,
      });
      message.success("配置已保存");
    } catch (error) {
      message.error("保存失败");
    } finally {
      setLoading(false);
    }
  };

  return (
    <>
      {/* 系统统计信息 */}
      {stats && (
        <Card title="系统统计" style={{ marginBottom: 24 }}>
          <Row gutter={16}>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="总用户数" value={stats.totalUsers} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="活跃用户" value={stats.activeUsers} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="今日新用户" value={stats.newUsersToday} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="商品总数" value={stats.totalProducts} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="活跃商品" value={stats.activeProducts} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="订单总数" value={stats.totalOrders} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic title="待处理订单" value={stats.pendingOrders} />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic
                title="总营收"
                value={`$${stats.totalRevenue.toFixed(2)}`}
              />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic
                title="今日营收"
                value={`$${stats.revenueToday.toFixed(2)}`}
              />
            </Col>
            <Col xs={24} sm={12} md={6}>
              <Statistic
                title="最后更新"
                value={
                  stats.lastUpdateTime
                    ? dayjs(stats.lastUpdateTime).format("HH:mm")
                    : "-"
                }
              />
            </Col>
          </Row>
        </Card>
      )}

      {/* 应用配置 */}
      <Card title="应用配置">
        <Form
          form={form}
          layout="vertical"
          onFinish={handleSave}
          autoComplete="off"
        >
          <Divider>基本信息</Divider>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label="应用名称" name="appName">
                <Input placeholder="应用名称" />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label="应用版本" name="appVersion">
                <Input placeholder="应用版本" />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item label="应用描述" name="appDescription">
            <Input.TextArea placeholder="应用描述" rows={3} />
          </Form.Item>

          <Divider>联系方式</Divider>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label="客服邮箱" name="supportEmail">
                <Input type="email" placeholder="support@example.com" />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label="客服电话" name="supportPhone">
                <Input placeholder="+86-123-4567-8900" />
              </Form.Item>
            </Col>
          </Row>

          <Divider>交易设置</Divider>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item label="默认币种" name="defaultCurrency">
                <Select
                  placeholder="选择默认币种"
                  options={currencies.map((currency) => ({
                    label: `${currency.currencyName} (${currency.currencyCode})`,
                    value: currency.currencyCode,
                  }))}
                />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label="满额免运费金额" name="freeshippingThreshold">
                <InputNumber placeholder="0" min={0} step={1} />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label="默认运费" name="shippingFee">
                <InputNumber placeholder="0" min={0} step={0.01} />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item label="最大上传文件大小 (MB)" name="maxUploadSize">
                <InputNumber placeholder="10" min={1} step={1} />
              </Form.Item>
            </Col>
          </Row>

          <Divider>功能开关</Divider>

          <Row gutter={16}>
            <Col xs={24} md={12}>
              <Form.Item
                label="启用用户注册"
                name="enableUserRegistration"
                valuePropName="checked"
              >
                <Switch />
              </Form.Item>
            </Col>
            <Col xs={24} md={12}>
              <Form.Item
                label="启用卖家注册"
                name="enableSellerRegistration"
                valuePropName="checked"
              >
                <Switch />
              </Form.Item>
            </Col>
          </Row>

          <Divider>首页配置</Divider>

          <Form.Item label="主页轮播图" name="carouselImages">
            <Upload
              listType="picture-card"
              fileList={carouselFiles}
              onChange={({ fileList }) =>
                setCarouselFiles(
                  fileList.map((file) => ({
                    ...file,
                    url: normalizeImageUrl(file.url || file.response?.data),
                  })),
                )
              }
              customRequest={async ({ file, onSuccess, onError }) => {
                try {
                  const response = await uploadProductImages(file as File);
                  onSuccess?.({ data: normalizeImageForSave(response.data) });
                } catch (error) {
                  onError?.(error as Error);
                }
              }}
            >
              {carouselFiles.length >= 8 ? null : "+"}
            </Upload>
          </Form.Item>

          <Form.Item>
            <Space>
              <Button type="primary" htmlType="submit" loading={loading}>
                保存配置
              </Button>
              <Button onClick={loadSettings}>重置</Button>
            </Space>
          </Form.Item>
        </Form>
      </Card>
    </>
  );
};

export default AdminSettings;

// shop-vue/src/pages/admin/settings/index.vue
<template>
  <div>
    <!-- System Stats -->
    <a-card v-if="stats" title="系统统计" :bordered="false" style="margin-bottom: 24px">
      <a-row :gutter="16">
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="总用户数" :value="stats.totalUsers" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="活跃用户" :value="stats.activeUsers" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="今日新用户" :value="stats.newUsersToday" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="商品总数" :value="stats.totalProducts" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="活跃商品" :value="stats.activeProducts" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="订单总数" :value="stats.totalOrders" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="待处理订单" :value="stats.pendingOrders" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="总营收" :value="stats.totalRevenue" prefix="$" :precision="2" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic title="今日营收" :value="stats.revenueToday" prefix="$" :precision="2" />
        </a-col>
        <a-col :xs="24" :sm="12" :md="6">
          <a-statistic
            title="最后更新"
            :value="stats.lastUpdateTime ? dayjs(stats.lastUpdateTime).format('HH:mm') : '-'"
          />
        </a-col>
      </a-row>
    </a-card>

    <!-- App Config -->
    <a-card title="应用配置" :bordered="false">
      <a-form
        ref="formRef"
        :model="formData"
        layout="vertical"
      >
        <a-divider>基本信息</a-divider>

        <a-row :gutter="16">
          <a-col :xs="24" :md="12">
            <a-form-item label="应用名称" name="appName">
              <a-input v-model:value="formData.appName" placeholder="应用名称" />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="应用版本" name="appVersion">
              <a-input v-model:value="formData.appVersion" placeholder="应用版本" />
            </a-form-item>
          </a-col>
        </a-row>

        <a-form-item label="应用描述" name="appDescription">
          <a-textarea v-model:value="formData.appDescription" placeholder="应用描述" :rows="3" />
        </a-form-item>

        <a-divider>联系方式</a-divider>

        <a-row :gutter="16">
          <a-col :xs="24" :md="12">
            <a-form-item label="客服邮箱" name="supportEmail">
              <a-input v-model:value="formData.supportEmail" type="email" placeholder="support@example.com" />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="客服电话" name="supportPhone">
              <a-input v-model:value="formData.supportPhone" placeholder="+86-123-4567-8900" />
            </a-form-item>
          </a-col>
        </a-row>

        <a-divider>交易设置</a-divider>

        <a-row :gutter="16">
          <a-col :xs="24" :md="12">
            <a-form-item label="默认币种" name="defaultCurrency">
              <a-select
                v-model:value="formData.defaultCurrency"
                placeholder="选择默认币种"
                :options="currencyOptions"
              />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="包邮门槛" name="freeshippingThreshold">
              <a-input-number
                v-model:value="formData.freeshippingThreshold"
                placeholder="0"
                :min="0"
                :step="1"
                style="width: 100%"
              />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="运费" name="shippingFee">
              <a-input-number
                v-model:value="formData.shippingFee"
                placeholder="0"
                :min="0"
                :step="0.01"
                style="width: 100%"
              />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="最大上传大小(MB)" name="maxUploadSize">
              <a-input-number
                v-model:value="formData.maxUploadSize"
                placeholder="10"
                :min="1"
                :step="1"
                style="width: 100%"
              />
            </a-form-item>
          </a-col>
        </a-row>

        <a-divider>功能开关</a-divider>

        <a-row :gutter="16">
          <a-col :xs="24" :md="12">
            <a-form-item label="允许用户注册" name="enableUserRegistration">
              <a-switch v-model:checked="formData.enableUserRegistration" />
            </a-form-item>
          </a-col>
          <a-col :xs="24" :md="12">
            <a-form-item label="允许卖家注册" name="enableSellerRegistration">
              <a-switch v-model:checked="formData.enableSellerRegistration" />
            </a-form-item>
          </a-col>
        </a-row>

        <a-divider>首页轮播图</a-divider>

        <a-form-item label="轮播图片">
          <a-upload
            list-type="picture-card"
            :file-list="carouselFiles"
            :custom-request="handleUpload"
            @preview="handlePreview"
            @remove="handleRemove"
          >
            <div v-if="carouselFiles.length < 8">
              <PlusOutlined />
              <div style="margin-top: 8px">上传</div>
            </div>
          </a-upload>
        </a-form-item>

        <a-form-item>
          <a-space>
            <a-button type="primary" :loading="saving" @click="handleSave">
              保存配置
            </a-button>
            <a-button @click="loadSettings">重置</a-button>
          </a-space>
        </a-form-item>
      </a-form>
    </a-card>

    <!-- Preview Modal -->
    <a-modal
      v-model:open="previewVisible"
      :footer="null"
      title="图片预览"
    >
      <img :src="previewImage" alt="preview" style="width: 100%" />
    </a-modal>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue'
import { message } from 'ant-design-vue'
import { PlusOutlined } from '@ant-design/icons-vue'
import dayjs from 'dayjs'
import { getAppConfig, updateAppConfig, getSystemStats } from '@/services/settings'
import { getCurrencies } from '@/services/rate'
import request from '@/utils/request'
import type { SystemStats, AppConfig } from '@/models/settings'
import type { Currency } from '@/models/rate'
import type { UploadFile, UploadProps } from 'ant-design-vue'

const saving = ref(false)
const stats = ref<SystemStats | null>(null)
const currencies = ref<Currency[]>([])
const carouselFiles = ref<UploadFile[]>([])

const previewVisible = ref(false)
const previewImage = ref('')

const formRef = ref()

const formData = reactive<AppConfig>({
  appName: '',
  appVersion: '',
  appDescription: '',
  supportEmail: '',
  supportPhone: '',
  defaultCurrency: undefined,
  freeshippingThreshold: undefined,
  shippingFee: undefined,
  maxUploadSize: undefined,
  enableUserRegistration: false,
  enableSellerRegistration: false,
})

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || 'http://localhost:8080/api'

const normalizeImageUrl = (url?: string): string => {
  if (!url) return ''
  if (url.startsWith('http')) return url
  return `${API_BASE_URL}${url.startsWith('/') ? url : `/${url}`}`
}

const normalizeImageForSave = (url?: string): string => {
  if (!url) return ''
  if (url.startsWith(API_BASE_URL)) {
    const rest = url.slice(API_BASE_URL.length)
    return rest.startsWith('/') ? rest : `/${rest}`
  }
  return url
}

const currencyOptions = computed(() =>
  currencies.value.map((c) => ({
    label: `${c.currencyName} (${c.currencyCode})`,
    value: c.currencyCode,
  }))
)

const loadSettings = async () => {
  try {
    const response = await getAppConfig()
    const config = response.data
    if (config) {
      formData.appName = config.appName || ''
      formData.appVersion = config.appVersion || ''
      formData.appDescription = config.appDescription || ''
      formData.supportEmail = config.supportEmail || ''
      formData.supportPhone = config.supportPhone || ''
      formData.defaultCurrency = config.defaultCurrency
      formData.freeshippingThreshold = config.freeshippingThreshold
      formData.shippingFee = config.shippingFee
      formData.maxUploadSize = config.maxUploadSize
      formData.enableUserRegistration = config.enableUserRegistration || false
      formData.enableSellerRegistration = config.enableSellerRegistration || false

      const images = config.carouselImages || []
      carouselFiles.value = images.map((url, index) => ({
        uid: `${index}`,
        name: `carousel-${index}`,
        status: 'done' as const,
        url: normalizeImageUrl(url),
      }))
    }
  } catch {
    message.error('加载配置失败')
  }
}

const loadStats = async () => {
  try {
    const response = await getSystemStats()
    stats.value = response.data || null
  } catch {
    console.error('Failed to load stats')
  }
}

const loadCurrencies = async () => {
  try {
    const response = await getCurrencies()
    currencies.value = response.data || []
  } catch {
    console.error('Failed to load currencies')
  }
}

const handleUpload: UploadProps['customRequest'] = async (options) => {
  const { file, onSuccess, onError } = options
  try {
    const fd = new FormData()
    fd.append('file', file as File)
    const response: any = await request({
      url: '/file/upload',
      method: 'POST',
      data: fd,
      headers: { 'Content-Type': 'multipart/form-data' },
    })
    const relativePath = response.data
    const newFile: UploadFile = {
      uid: `upload-${Date.now()}`,
      name: (file as File).name,
      status: 'done',
      url: normalizeImageUrl(relativePath),
      response: { data: relativePath },
    }
    carouselFiles.value = [...carouselFiles.value, newFile]
    onSuccess?.(response)
  } catch (error) {
    onError?.(error as Error)
    message.error('上传失败')
  }
}

const handlePreview = (file: UploadFile) => {
  previewImage.value = file.url || ''
  previewVisible.value = true
}

const handleRemove = (file: UploadFile) => {
  carouselFiles.value = carouselFiles.value.filter((f) => f.uid !== file.uid)
  return true
}

const handleSave = async () => {
  saving.value = true
  try {
    const carouselImages = carouselFiles.value
      .map((file) => file.response?.data || file.url)
      .map((url) => normalizeImageForSave(url))
      .filter(Boolean) as string[]

    await updateAppConfig({
      ...formData,
      carouselImages,
    })
    message.success('配置已保存')
  } catch {
    message.error('保存失败')
  } finally {
    saving.value = false
  }
}

onMounted(() => {
  loadSettings()
  loadStats()
  loadCurrencies()
})
</script>
