// shop-vue/src/pages/user/profile.vue
<template>
  <a-card v-if="!currentUser">
    <div style="text-align: center; padding: 50px">请先登录</div>
  </a-card>
  <a-card v-else title="个人信息">
    <template #extra>
      <a-button type="primary" disabled>
        <template #icon><EditOutlined /></template>
        编辑资料
      </a-button>
    </template>
    <a-descriptions :column="2" bordered>
      <a-descriptions-item label="用户ID">{{ currentUser.id }}</a-descriptions-item>
      <a-descriptions-item label="用户名">{{ currentUser.username }}</a-descriptions-item>
      <a-descriptions-item label="昵称">{{ currentUser.nickname || '-' }}</a-descriptions-item>
      <a-descriptions-item label="邮箱">{{ currentUser.email || '-' }}</a-descriptions-item>
      <a-descriptions-item label="手机号">{{ currentUser.phone || '-' }}</a-descriptions-item>
      <a-descriptions-item label="角色名称">{{ currentUser.roles?.[0]?.roleName || '-' }}</a-descriptions-item>
      <a-descriptions-item label="角色代码">{{ currentUser.roles?.[0]?.roleCode || '-' }}</a-descriptions-item>
      <a-descriptions-item label="角色描述" :span="2">{{ currentUser.roles?.[0]?.description || '-' }}</a-descriptions-item>
      <a-descriptions-item label="状态">
        <a-tag v-if="currentUser.status === 1" color="success">正常</a-tag>
        <a-tag v-else color="error">禁用</a-tag>
      </a-descriptions-item>
      <a-descriptions-item label="创建时间" :span="2">{{ currentUser.createTime || '-' }}</a-descriptions-item>
      <a-descriptions-item v-if="currentUser.lastLoginTime" label="最后登录" :span="2">
        {{ currentUser.lastLoginTime }}
      </a-descriptions-item>
    </a-descriptions>
  </a-card>
</template>

<script setup lang="ts">
import { computed } from 'vue'
import { EditOutlined } from '@ant-design/icons-vue'
import { useUserStore } from '@/stores/user'

const userStore = useUserStore()
const currentUser = computed(() => userStore.currentUser)
</script>

// .shop/src/pages/user/profile.tsx
import { Card, Descriptions, Button, Space, Tag } from "antd";
import { EditOutlined } from "@ant-design/icons";
import { getUserInfo } from "@/utils/request";

const UserProfile: React.FC = () => {
  const user = getUserInfo();

  if (!user) {
    return (
      <Card>
        <div style={{ textAlign: "center", padding: "50px" }}>请先登录</div>
      </Card>
    );
  }

  const getStatusTag = (status?: number) => {
    if (status === 1) {
      return <Tag color="success">正常</Tag>;
    }
    return <Tag color="error">禁用</Tag>;
  };

  return (
    <Card
      title="个人信息"
      extra={
        <Space>
          <Button type="primary" icon={<EditOutlined />} disabled>
            编辑资料
          </Button>
        </Space>
      }
    >
      <Descriptions column={2} bordered>
        <Descriptions.Item label="用户ID">{user.id}</Descriptions.Item>
        <Descriptions.Item label="用户名">{user.username}</Descriptions.Item>
        {user.name && (
          <Descriptions.Item label="姓名">{user.name}</Descriptions.Item>
        )}
        <Descriptions.Item label="邮箱">{user.email || "-"}</Descriptions.Item>
        <Descriptions.Item label="手机号">
          {user.phone || "-"}
        </Descriptions.Item>
        <Descriptions.Item label="角色名称">
          {user.roles?.[0]?.roleName || "-"}
        </Descriptions.Item>
        <Descriptions.Item label="角色代码">
          {user.roles?.[0]?.roleCode || "-"}
        </Descriptions.Item>
        <Descriptions.Item label="角色描述" span={2}>
          {user.roles?.[0]?.description || "-"}
        </Descriptions.Item>
        <Descriptions.Item label="状态">
          {getStatusTag(user.status)}
        </Descriptions.Item>
        <Descriptions.Item label="创建时间" span={2}>
          {user.createdAt || "-"}
        </Descriptions.Item>
        {user.lastLoginAt && (
          <Descriptions.Item label="最后登录时间" span={2}>
            {user.lastLoginAt}
          </Descriptions.Item>
        )}
      </Descriptions>
    </Card>
  );
};

export default UserProfile;
