// user/src/components/CategoryNav/index.tsx
import React, { useEffect, useState } from 'react';
import { Menu } from 'antd';
import { AppstoreOutlined } from '@ant-design/icons';
import { useNavigate, useLocation } from '@umijs/renderer-react';
import { useTranslation } from 'react-i18next';
import { getCategoryList } from '@/services/category';
import type { Category } from '@/models/category';

import styles from './index.module.css';

const CategoryNav: React.FC = () => {
  const { t, i18n } = useTranslation();
  const navigate = useNavigate();
  const [categories, setCategories] = useState<Category[]>([]);
  const location = useLocation();

  useEffect(() => {
    loadCategories();
  }, []);

  const loadCategories = async () => {
    try {
      const response = await getCategoryList();
      setCategories(response.data);
    } catch (error) {
      console.error('Failed to load categories:', error);
    }
  };

  const handleCategoryClick = (categoryId: number) => {
    navigate(`/products?category=${categoryId}`);
  };

  const getCategoryLabel = (category: Category) => {
    return i18n.language === 'zh-CN' ? category.categoryName : category.categoryCode;
  };

  const items = [
    {
      key: 'all',
      icon: <AppstoreOutlined />,
      label: t('product.allProducts'),
      onClick: () => navigate('/products'),
    },
    ...categories.map((category) => ({
      key: category.id.toString(),
      label: getCategoryLabel(category),
      onClick: () => handleCategoryClick(category.id),
    })),
  ];

  return (
    <div className={styles.categoryNav}>
      <Menu
        mode="horizontal"
        items={items}
        selectedKeys={[]}
        className={styles.menu}
      />
    </div>
  );
};

export default CategoryNav;

// user-vue/src/components/CategoryNav.vue
<template>
  <div class="category-nav">
    <a-menu
      mode="horizontal"
      :items="items"
      :selectedKeys="[]"
      class="menu"
    />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, computed, h } from 'vue'
import { useRouter } from 'vue-router'
import { AppstoreOutlined } from '@ant-design/icons-vue'
import { getCategoryList } from '@/services/category'
import { useI18n } from '@/i18n'
import type { Category } from '@/models/category'

const router = useRouter()
const { t, i18n } = useI18n()
const categories = ref<Category[]>([])

onMounted(() => {
  loadCategories()
})

const loadCategories = async () => {
  try {
    const response = await getCategoryList()
    categories.value = response.data || []
  } catch (error) {
    console.error('Failed to load categories:', error)
  }
}

const handleCategoryClick = (categoryId: number) => {
  router.push(`/products?category=${categoryId}`)
}

const getCategoryLabel = (category: Category) => {
  return i18n.language === 'zh-CN' ? category.categoryName : category.categoryCode
}

const items = computed(() => [
  {
    key: 'all',
    icon: () => h(AppstoreOutlined),
    label: t('product.allProducts'),
    onClick: () => router.push('/products'),
  },
  ...categories.value.map((category: Category) => ({
    key: category.id.toString(),
    label: getCategoryLabel(category),
    onClick: () => handleCategoryClick(category.id),
  })),
])
</script>

<style scoped>
.category-nav {
  background-color: white;
  border-bottom: 1px solid #f0f0f0;
  padding: 0;
}

.menu {
  border: none !important;
}
</style>
