// shop-vue/src/pages/orders/index.vue
<template>
  <div>
    <!-- Search Form -->
    <a-card :bordered="false" style="margin-bottom: 16px">
      <a-form layout="inline" :model="searchForm" @finish="handleSearch">
        <a-form-item label="订单状态">
          <a-select
            v-model:value="searchForm.orderStatus"
            placeholder="请选择订单状态"
            allow-clear
            style="width: 180px"
          >
            <a-select-option :value="OrderStatus.PENDING">待支付</a-select-option>
            <a-select-option :value="OrderStatus.PAID">已支付</a-select-option>
            <a-select-option :value="OrderStatus.SHIPPED">已发货</a-select-option>
            <a-select-option :value="OrderStatus.COMPLETED">已完成</a-select-option>
            <a-select-option :value="OrderStatus.CANCELED">已取消</a-select-option>
            <a-select-option :value="OrderStatus.REFUNDING">退款中</a-select-option>
            <a-select-option :value="OrderStatus.REFUNDED">已退款</a-select-option>
          </a-select>
        </a-form-item>
        <a-form-item>
          <a-space>
            <a-button type="primary" html-type="submit">搜索</a-button>
            <a-button @click="handleReset">重置</a-button>
          </a-space>
        </a-form-item>
      </a-form>
    </a-card>

    <!-- Table -->
    <a-card title="订单列表" :bordered="false">
      <a-table
        :columns="columns"
        :data-source="dataSource"
        :loading="loading"
        :pagination="{ pageSize: 10, showSizeChanger: true, showTotal: (t: number) => `共 ${t} 条` }"
        row-key="id"
        :scroll="{ x: 1200 }"
      >
        <template #bodyCell="{ column, record }">
          <template v-if="column.dataIndex === 'orderNumber'">
            <a-typography-paragraph :copyable="{ text: record.orderNumber }" style="margin: 0">
              {{ record.orderNumber }}
            </a-typography-paragraph>
          </template>
          <template v-else-if="column.dataIndex === 'totalAmount'">
            ¥{{ (record.totalAmount || 0).toFixed(2) }}
          </template>
          <template v-else-if="column.dataIndex === 'productAmount'">
            {{ record.productAmount ? `¥${record.productAmount.toFixed(2)}` : '-' }}
          </template>
          <template v-else-if="column.dataIndex === 'freightAmount'">
            {{ record.freightAmount ? `¥${record.freightAmount.toFixed(2)}` : '-' }}
          </template>
          <template v-else-if="column.dataIndex === 'orderStatus'">
            <a-tag :color="orderStatusMap[record.orderStatus as OrderStatus]?.color || 'default'">
              {{ orderStatusMap[record.orderStatus as OrderStatus]?.text || '未知' }}
            </a-tag>
          </template>
          <template v-else-if="column.dataIndex === 'paymentStatus'">
            <template v-if="record.paymentStatus !== undefined && record.paymentStatus !== null">
              <a-tag :color="paymentStatusMap[record.paymentStatus as PaymentStatus]?.color || 'default'">
                {{ paymentStatusMap[record.paymentStatus as PaymentStatus]?.text || '未知' }}
              </a-tag>
            </template>
            <template v-else>-</template>
          </template>
          <template v-else-if="column.key === 'action'">
            <a-button type="link" size="small" @click="router.push(`/orders/${record.id}`)">
              <EyeOutlined /> 查看详情
            </a-button>
          </template>
        </template>
      </a-table>
    </a-card>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { EyeOutlined } from '@ant-design/icons-vue'
import { getOrderList } from '@/services/order'
import { OrderStatus, PaymentStatus } from '@/models/order'
import type { Order } from '@/models/order'

const router = useRouter()
const loading = ref(false)
const dataSource = ref<Order[]>([])

const searchForm = reactive({
  orderStatus: undefined as OrderStatus | undefined,
})

const orderStatusMap: Record<OrderStatus, { color: string; text: string }> = {
  [OrderStatus.PENDING]: { color: 'default', text: '待支付' },
  [OrderStatus.PAID]: { color: 'processing', text: '已支付' },
  [OrderStatus.SHIPPED]: { color: 'blue', text: '已发货' },
  [OrderStatus.COMPLETED]: { color: 'success', text: '已完成' },
  [OrderStatus.CANCELED]: { color: 'error', text: '已取消' },
  [OrderStatus.REFUNDING]: { color: 'warning', text: '退款中' },
  [OrderStatus.REFUNDED]: { color: 'default', text: '已退款' },
}

const paymentStatusMap: Record<PaymentStatus, { color: string; text: string }> = {
  [PaymentStatus.UNPAID]: { color: 'default', text: '未支付' },
  [PaymentStatus.PAID]: { color: 'success', text: '已支付' },
  [PaymentStatus.REFUNDED]: { color: 'error', text: '已退款' },
}

const columns = [
  { title: '订单编号', dataIndex: 'orderNumber', width: 180 },
  { title: '买家ID', dataIndex: 'buyerId', width: 100 },
  { title: '订单金额', dataIndex: 'totalAmount', width: 120 },
  { title: '商品金额', dataIndex: 'productAmount', width: 120 },
  { title: '运费', dataIndex: 'freightAmount', width: 100 },
  { title: '订单状态', dataIndex: 'orderStatus', width: 100 },
  { title: '支付状态', dataIndex: 'paymentStatus', width: 100 },
  { title: '创建时间', dataIndex: 'createTime', width: 180 },
  { title: '操作', key: 'action', width: 120, fixed: 'right' as const },
]

const fetchData = async () => {
  loading.value = true
  try {
    const response = await getOrderList({
      orderStatus: searchForm.orderStatus,
    } as any)

    // Handle both array and PageResult format
    const data = response.data
    if (Array.isArray(data)) {
      dataSource.value = data
    } else if (data && typeof data === 'object') {
      dataSource.value = (data as any).list || []
    } else {
      dataSource.value = []
    }
  } catch {
    message.error('加载订单列表失败')
  } finally {
    loading.value = false
  }
}

const handleSearch = () => {
  fetchData()
}

const handleReset = () => {
  searchForm.orderStatus = undefined
  fetchData()
}

onMounted(() => {
  fetchData()
})
</script>

// user/src/pages/user/orders/index.tsx
import React, { useEffect, useState } from "react";
import { Card, Table, Tag, Button, message, Space } from "antd";
import { EyeOutlined } from "@ant-design/icons";
import { useNavigate } from "@umijs/renderer-react";
import { getOrderList } from "@/services/order";
import type { Order } from "@/models/order";
import styles from "./index.module.css";

const OrderListPage: React.FC = () => {
  const [orders, setOrders] = useState<Order[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    loadOrders();
  }, [page]);

  const loadOrders = async () => {
    try {
      setLoading(true);
      const response = await getOrderList({ page, pageSize });
      console.log("订单列表响应:", response);
      if (response.data) {
        setOrders(response.data.list || []);
        setTotal(response.data.total || 0);
      }
    } catch (error) {
      console.error("Failed to load orders:", error);
      message.error("加载订单列表失败");
    } finally {
      setLoading(false);
    }
  };

  const getStatusText = (status: number) => {
    const statusMap: Record<number, string> = {
      0: "待支付",
      1: "已支付",
      2: "已发货",
      3: "已完成",
      4: "已取消",
      5: "退款中",
      6: "已退款",
    };
    return statusMap[status] || "未知";
  };

  const getStatusColor = (status: number) => {
    const colorMap: Record<number, string> = {
      0: "orange",
      1: "blue",
      2: "cyan",
      3: "green",
      4: "red",
      5: "purple",
      6: "default",
    };
    return colorMap[status] || "default";
  };

  const columns = [
    {
      title: "订单号",
      dataIndex: "orderNo",
      key: "orderNo",
      render: (orderNo: string) => orderNo || "-",
    },
    {
      title: "创建时间",
      dataIndex: "createdAt",
      key: "createdAt",
      render: (date: string) =>
        date ? new Date(date).toLocaleString("zh-CN") : "-",
    },
    {
      title: "订单金额",
      dataIndex: "totalAmount",
      key: "totalAmount",
      render: (amount: number) => `¥${(amount || 0).toFixed(2)}`,
    },
    {
      title: "实付金额",
      dataIndex: "actualAmount",
      key: "actualAmount",
      render: (amount: number) => `¥${(amount || 0).toFixed(2)}`,
    },
    {
      title: "订单状态",
      dataIndex: "status",
      key: "status",
      render: (status: number) => (
        <Tag color={getStatusColor(status)}>{getStatusText(status)}</Tag>
      ),
    },
    {
      title: "操作",
      key: "action",
      render: (record: Order) => (
        <Button
          type="link"
          icon={<EyeOutlined />}
          onClick={() => navigate(`/user/orders/${record.id}`)}
        >
          查看详情
        </Button>
      ),
    },
  ];

  return (
    <div className={styles.orderListPage}>
      <div className={styles.container}>
        <h1 className={styles.title}>我的订单</h1>

        <Card className={styles.card}>
          <Table
            dataSource={orders}
            columns={columns}
            rowKey="id"
            loading={loading}
            pagination={{
              current: page,
              pageSize,
              total,
              onChange: (p) => setPage(p),
              showTotal: (total) => `共 ${total} 条订单`,
            }}
          />
        </Card>
      </div>
    </div>
  );
};

export default OrderListPage;
