// user-vue/src/components/Header.vue
<template>
  <a-layout-header class="header">
    <div class="container">
      <!-- Logo -->
      <div class="logo" @click="handleLogoClick">
        CrossBorder Shop
      </div>

      <!-- Search Bar -->
      <div class="search">
        <a-input-search
          :placeholder="t('product.search')"
          allow-clear
          size="large"
          @search="handleSearch"
        >
          <template #enterButton>
            <SearchOutlined />
          </template>
        </a-input-search>
      </div>

      <!-- Desktop Actions -->
      <div class="actions">
        <a-space size="large">
          <LanguageSwitcher />
          <a-badge :count="cartCount" :show-zero="true">
            <ShoppingCartOutlined class="icon" @click="handleGoToCart" />
          </a-badge>
          <a-dropdown :menu="{ items: userMenuItems }" placement="bottomRight">
            <UserOutlined class="icon" />
          </a-dropdown>
        </a-space>
      </div>

      <!-- Mobile Menu -->
      <div class="mobileMenu">
        <a-space size="middle">
          <LanguageSwitcher />
          <a-badge :count="cartCount" :show-zero="true">
            <ShoppingCartOutlined class="icon" @click="handleGoToCart" />
          </a-badge>
          <a-dropdown :menu="{ items: userMenuItems }" placement="bottomRight">
            <MenuOutlined class="icon" />
          </a-dropdown>
        </a-space>
      </div>
    </div>
  </a-layout-header>
</template>

<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import {
  ShoppingCartOutlined,
  UserOutlined,
  SearchOutlined,
  MenuOutlined,
} from '@ant-design/icons-vue'
import { getToken, removeToken, removeRefreshToken, removeUserInfo } from '@/utils/request'
import { useI18n } from '@/i18n'
import LanguageSwitcher from '@/components/LanguageSwitcher.vue'
import type { MenuProps } from 'ant-design-vue'

const router = useRouter()
const { t } = useI18n()
const cartCount = ref(0)
const isLoggedIn = ref(false)

onMounted(() => {
  // Check if user is logged in
  const token = getToken()
  isLoggedIn.value = !!token

  // Get cart count from localStorage
  const cart = JSON.parse(localStorage.getItem('cart') || '[]')
  cartCount.value = cart.length

  // Listen for cart updates
  const handleCartUpdate = () => {
    const cart = JSON.parse(localStorage.getItem('cart') || '[]')
    cartCount.value = cart.length
  }

  window.addEventListener('storage', handleCartUpdate)

  // Cleanup on unmount
  return () => {
    window.removeEventListener('storage', handleCartUpdate)
  }
})

const handleSearch = (value: string) => {
  if (value.trim()) {
    router.push(`/products?search=${encodeURIComponent(value)}`)
  }
}

const handleLogoClick = () => {
  router.push('/')
}

const handleGoToCart = () => {
  router.push('/cart')
}

const handleLogout = () => {
  removeToken()
  removeRefreshToken()
  removeUserInfo()
  isLoggedIn.value = false
  router.push('/')
}

const userMenuItems = computed<MenuProps['items']>(() => {
  if (isLoggedIn.value) {
    return [
      {
        key: 'profile',
        label: t('nav.profile'),
        onClick: () => router.push('/user/profile'),
      },
      {
        key: 'orders',
        label: t('nav.orders'),
        onClick: () => router.push('/user/orders'),
      },
      {
        key: 'addresses',
        label: t('nav.addresses'),
        onClick: () => router.push('/user/addresses'),
      },
      {
        key: 'favorites',
        label: t('nav.favorites'),
        onClick: () => router.push('/user/favorites'),
      },
      {
        key: 'settings',
        label: t('nav.settings'),
        onClick: () => router.push('/user/settings'),
      },
      {
        type: 'divider',
      },
      {
        key: 'logout',
        label: t('nav.logout'),
        onClick: handleLogout,
      },
    ]
  } else {
    return [
      {
        key: 'login',
        label: t('nav.login'),
        onClick: () => router.push('/user/login'),
      },
      {
        key: 'register',
        label: t('nav.register'),
        onClick: () => router.push('/user/register'),
      },
    ]
  }
})
</script>

<style scoped>
.header {
  background: #fff;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
  padding: 0;
  position: sticky;
  top: 0;
  z-index: 999;
  line-height: 64px;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  height: 64px;
}

.logo {
  font-size: 24px;
  font-weight: bold;
  color: #1890ff;
  cursor: pointer;
  white-space: nowrap;
}

.search {
  flex: 1;
  max-width: 600px;
  margin: 0 40px;
  display: flex;
  justify-content: center;
}

.actions {
  display: flex;
  align-items: center;
}

.icon {
  font-size: 24px;
  cursor: pointer;
  color: #333;
  transition: color 0.3s;
}

.icon:hover {
  color: #1890ff;
}

.mobileMenu {
  display: none;
}

@media (max-width: 768px) {
  .container {
    padding: 0 16px;
  }

  .logo {
    font-size: 18px;
  }

  .search {
    display: none;
  }

  .actions {
    display: none;
  }

  .mobileMenu {
    display: flex;
  }

  .icon {
    font-size: 20px;
  }
}
</style>

// user/src/components/Header/index.tsx
import React, { useState, useEffect } from "react";
import { Layout, Input, Badge, Dropdown, Space, Button } from "antd";
import {
  ShoppingCartOutlined,
  UserOutlined,
  SearchOutlined,
  MenuOutlined,
} from "@ant-design/icons";
import { useNavigate } from "@umijs/renderer-react";
import { useTranslation } from "react-i18next";
import {
  removeToken,
  removeRefreshToken,
  removeUserInfo,
  getToken,
} from "@/utils/request";
import LanguageSwitcher from "@/components/LanguageSwitcher";
import type { MenuProps } from "antd";
import styles from "./index.module.css";

const { Header: AntHeader } = Layout;
const { Search } = Input;

const Header: React.FC = () => {
  const [cartCount, setCartCount] = useState(0);
  const [isLoggedIn, setIsLoggedIn] = useState(false);
  const navigate = useNavigate();
  const { t } = useTranslation();

  useEffect(() => {
    // Check if user is logged in
    const token = getToken();
    setIsLoggedIn(!!token);

    // Get cart count from localStorage
    const cart = JSON.parse(localStorage.getItem("cart") || "[]");
    setCartCount(cart.length);
  }, []);

  useEffect(() => {
    // Listen for cart updates
    const handleCartUpdate = () => {
      const cart = JSON.parse(localStorage.getItem("cart") || "[]");
      setCartCount(cart.length);
    };

    window.addEventListener("storage", handleCartUpdate);

    return () => {
      window.removeEventListener("storage", handleCartUpdate);
    };
  }, []);

  const handleSearch = (value: string) => {
    if (value.trim()) {
      navigate(`/products?search=${encodeURIComponent(value)}`);
    }
  };

  const userMenuItems: MenuProps["items"] = isLoggedIn
    ? [
        {
          key: "profile",
          label: t("nav.profile"),
          onClick: () => navigate("/user/profile"),
        },
        {
          key: "orders",
          label: t("nav.orders"),
          onClick: () => navigate("/user/orders"),
        },
        {
          key: "addresses",
          label: t("nav.addresses"),
          onClick: () => navigate("/user/addresses"),
        },
        {
          key: "favorites",
          label: t("nav.favorites"),
          onClick: () => navigate("/user/favorites"),
        },
        {
          key: "settings",
          label: t("nav.settings"),
          onClick: () => navigate("/user/settings"),
        },
        {
          type: "divider",
        },
        {
          key: "logout",
          label: t("nav.logout"),
          onClick: () => {
            removeToken();
            removeRefreshToken();
            removeUserInfo();
            setIsLoggedIn(false);
            navigate("/");
          },
        },
      ]
    : [
        {
          key: "login",
          label: t("nav.login"),
          onClick: () => navigate("/user/login"),
        },
        {
          key: "register",
          label: t("nav.register"),
          onClick: () => navigate("/user/register"),
        },
      ];

  return (
    <AntHeader className={styles.header}>
      <div className={styles.container}>
        <div className={styles.logo} onClick={() => navigate("/")}>
          CrossBorder Shop
        </div>

        <div className={styles.search}>
          <Search
            placeholder={t("product.search")}
            allowClear
            enterButton={<SearchOutlined />}
            size="large"
            onSearch={handleSearch}
          />
        </div>

        <div className={styles.actions}>
          <Space size="large">
            <LanguageSwitcher />
            <Badge count={cartCount} showZero>
              <ShoppingCartOutlined
                className={styles.icon}
                onClick={() => navigate("/cart")}
              />
            </Badge>

            <Dropdown menu={{ items: userMenuItems }} placement="bottomRight">
              <UserOutlined className={styles.icon} />
            </Dropdown>
          </Space>
        </div>

        <div className={styles.mobileMenu}>
          <Space size="middle">
            <LanguageSwitcher />
            <Badge count={cartCount} showZero>
              <ShoppingCartOutlined
                className={styles.icon}
                onClick={() => navigate("/cart")}
              />
            </Badge>
            <Dropdown menu={{ items: userMenuItems }} placement="bottomRight">
              <MenuOutlined className={styles.icon} />
            </Dropdown>
          </Space>
        </div>
      </div>
    </AntHeader>
  );
};

export default Header;
