// user/src/pages/user/orders/index.tsx
import React, { useEffect, useState } from "react";
import { Card, Table, Tag, Button, message } from "antd";
import { EyeOutlined } from "@ant-design/icons";
import { useNavigate } from "@umijs/renderer-react";
import { useTranslation } from "react-i18next";
import { getOrderList } from "@/services/order";
import type { Order } from "@/models/order";
import styles from "./index.module.css";

const OrderListPage: React.FC = () => {
  const { t } = useTranslation();
  const [orders, setOrders] = useState<Order[]>([]);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const [pageSize] = useState(10);
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  useEffect(() => {
    loadOrders();
  }, [page]);

  const loadOrders = async () => {
    try {
      setLoading(true);
      const response = await getOrderList({ page, pageSize });
      console.log("订单列表响应:", response);

      // Handle different response structures
      let orderList: Order[] = [];
      let totalCount = 0;
      
      if (Array.isArray(response)) {
        // If response is directly an array
        orderList = response;
        totalCount = response.length;
      } else if (Array.isArray(response.data)) {
        // If response.data is an array
        orderList = response.data;
        totalCount = response.data.length;
      } else if (response.data && response.data.list) {
        // If response.data has list property
        orderList = response.data.list;
        totalCount = response.data.total || response.data.list.length;
      }
      
      setOrders(orderList);
      setTotal(totalCount);
      
    } catch (error) {
      console.error("Failed to load orders:", error);
      message.error(t("common.error"));
    } finally {
      setLoading(false);
    }
  };

  const getStatusText = (status: number) => {
    const statusMap: Record<number, string> = {
      0: t("order.pending"),
      1: t("order.paid"),
      2: t("order.shipped"),
      3: t("order.completed"),
      4: t("order.cancelled"),
      5: t("order.refunding"),
      6: t("order.refunded"),
    };
    return statusMap[status] || t("common.info");
  };

  const getStatusColor = (status: number) => {
    const colorMap: Record<number, string> = {
      0: "orange",
      1: "blue",
      2: "cyan",
      3: "green",
      4: "red",
      5: "purple",
      6: "default",
    };
    return colorMap[status] || "default";
  };

  const columns = [
    {
      title: t("order.orderNo"),
      dataIndex: "orderNumber",
      key: "orderNumber",
      render: (orderNo: string) => orderNo || "-",
    },
    {
      title: t("order.createdAt"),
      dataIndex: "createTime",
      key: "createTime",
      render: (date: string) =>
        date ? new Date(date).toLocaleString("zh-CN") : "-",
    },
    {
      title: t("order.amount"),
      dataIndex: "totalAmount",
      key: "totalAmount",
      render: (amount: number) => `${amount ? amount.toFixed(2) : "0.00"}`,
    },
    {
      title: t("order.actualAmount"),
      dataIndex: "convertedAmount",
      key: "convertedAmount",
      render: (amount: number) => `${amount ? amount.toFixed(2) : "0.00"}`,
    },
    {
      title: t("order.status"),
      dataIndex: "orderStatus",
      key: "orderStatus",
      render: (status: number) => (
        <Tag color={getStatusColor(status)}>{getStatusText(status)}</Tag>
      ),
    },
    {
      title: t("common.edit"),
      key: "action",
      render: (record: Order) => (
        <Button
          type="link"
          icon={<EyeOutlined />}
          onClick={() => navigate(`/user/orders/${record.id}`)}
        >
          {t("order.viewDetails")}
        </Button>
      ),
    },
  ];

  return (
    <div className={styles.orderListPage}>
      <div className={styles.container}>
        <h1 className={styles.title}>{t("order.title")}</h1>

        <Card className={styles.card}>
          <Table
            dataSource={orders}
            columns={columns}
            rowKey="id"
            loading={loading}
            pagination={{
              current: page,
              pageSize,
              total,
              onChange: (p) => setPage(p),
              showTotal: (total) => `${t("order.totalProducts", { total })}`,
            }}
          />
        </Card>
      </div>
    </div>
  );
};

export default OrderListPage;

// user-vue/src/pages/user/orders/index.vue
<template>
  <div class="order-list-page">
    <div class="container">
      <h1 class="title">{{ t('order.title') }}</h1>

      <a-card class="card">
        <a-table
          :columns="columns"
          :data-source="orders"
          :loading="loading"
          :pagination="pagination"
          row-key="id"
          @change="handleTableChange"
        >
          <template #bodyCell="{ column, record }">
            <template v-if="column.key === 'createTime'">
              {{ formatDate(record.createTime) }}
            </template>
            <template v-else-if="column.key === 'totalAmount'">
              {{ record.totalAmount?.toFixed(2) || '0.00' }}
            </template>
            <template v-else-if="column.key === 'convertedAmount'">
              {{ record.convertedAmount?.toFixed(2) || '0.00' }}
            </template>
            <template v-else-if="column.key === 'orderStatus'">
              <a-tag :color="getStatusColor(record.orderStatus)">
                {{ getStatusText(record.orderStatus) }}
              </a-tag>
            </template>
            <template v-else-if="column.key === 'action'">
              <a-button type="link" @click="goToDetail(record.id)">
                <template #icon>
                  <EyeOutlined />
                </template>
                {{ t('order.viewDetails') }}
              </a-button>
            </template>
          </template>
        </a-table>
      </a-card>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, computed } from 'vue'
import { useI18n } from '@/i18n'
import { useRouter } from 'vue-router'
import { message } from 'ant-design-vue'
import { EyeOutlined } from '@ant-design/icons-vue'
import type { Order, OrderListParams } from '@/models/order'
import { OrderStatus } from '@/models/order'
import { getOrderList } from '@/services/order'

const { t } = useI18n()
const router = useRouter()

const orders = ref<Order[]>([])
const loading = ref(false)
const page = ref(1)
const pageSize = ref(10)
const total = ref(0)

const pagination = computed(() => ({
  current: page.value,
  pageSize: pageSize.value,
  total: total.value,
  showTotal: (total: number) => `Total: ${total} items`,
}))

const columns = [
  {
    title: t('order.orderNo'),
    dataIndex: 'orderNumber',
    key: 'orderNumber',
  },
  {
    title: t('order.createdAt'),
    key: 'createTime',
  },
  {
    title: t('order.amount'),
    key: 'totalAmount',
  },
  {
    title: t('order.actualAmount'),
    key: 'convertedAmount',
  },
  {
    title: t('order.status'),
    key: 'orderStatus',
  },
  {
    title: t('common.edit'),
    key: 'action',
  },
]

const statusMap: Record<number, string> = {
  [OrderStatus.PENDING]: 'orange',
  [OrderStatus.PAID]: 'blue',
  [OrderStatus.SHIPPED]: 'cyan',
  [OrderStatus.COMPLETED]: 'green',
  [OrderStatus.CANCELED]: 'red',
  [OrderStatus.REFUNDING]: 'purple',
  [OrderStatus.REFUNDED]: 'default',
}

const statusTextMap: Record<number, string> = {
  [OrderStatus.PENDING]: t('order.pending'),
  [OrderStatus.PAID]: t('order.paid'),
  [OrderStatus.SHIPPED]: t('order.shipped'),
  [OrderStatus.COMPLETED]: t('order.completed'),
  [OrderStatus.CANCELED]: t('order.cancelled'),
  [OrderStatus.REFUNDING]: t('order.refunding'),
  [OrderStatus.REFUNDED]: t('order.refunded'),
}

onMounted(() => {
  loadOrders()
})

const loadOrders = async () => {
  try {
    loading.value = true
    const params: OrderListParams = {
      page: page.value,
      pageSize: pageSize.value,
    }
    const response = await getOrderList(params)

    // Handle different response structures
    if (response.data) {
      orders.value = response.data.list || response.data
      total.value = response.data.total || (Array.isArray(response.data) ? response.data.length : 0)
    } else {
      orders.value = []
      total.value = 0
    }
  } catch (error) {
    console.error('Failed to load orders:', error)
    message.error(t('common.error'))
  } finally {
    loading.value = false
  }
}

const getStatusText = (status: number) => {
  return statusTextMap[status] || t('common.info')
}

const getStatusColor = (status: number) => {
  return statusMap[status] || 'default'
}

const formatDate = (dateString: string) => {
  return new Date(dateString).toLocaleString()
}

const handleTableChange = (pag: any) => {
  page.value = pag.current
  pageSize.value = pag.pageSize
  loadOrders()
}

const goToDetail = (orderId: number) => {
  router.push(`/user/orders/${orderId}`)
}
</script>

<style scoped>
.order-list-page {
  min-height: calc(100vh - 64px - 200px);
  background: #f5f5f5;
  padding: 24px 0;
}

.container {
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 24px;
}

.title {
  font-size: 28px;
  font-weight: bold;
  margin-bottom: 24px;
}

.card {
  border-radius: 8px;
}

@media (max-width: 768px) {
  .container {
    padding: 0 16px;
  }

  .title {
    font-size: 22px;
  }
}
</style>
